version: '2.4'

services:
  readsb:
    image: docker.io/blackoutsecure/readsb:latest
    container_name: readsb
    environment:
      TZ: Etc/UTC
      PUID: '1000'
      PGID: '1000'
      READSB_ARGS: '--net --device-type rtlsdr'
      READSB_AUTO_LOCATION: 'true'
    volumes:
      - config:/config
      - json:/run/readsb
    devices:
      - /dev/bus/usb:/dev/bus/usb
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    ports:
      - '30001:30001'
      - '30002:30002'
      - '30003:30003'
      - '30004:30004'
      - '30005:30005'
      - '30104:30104'
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /run:exec
    read_only: false
    restart: unless-stopped

volumes:
  config:
  json:
